### PR TITLE
Fixing handler issue and used ami permissions

### PR DESCRIPTION
**Pull request by guilhermeassad**

### CODE REVIEW

**Comment by dynamike** [comment]
Can you say more about what this PR is doing. I see you've passed in a handler and added EC2 permissions to the IAM role, but am unsure why these changes are being made

**Comment by guilhermeassad** [comment]
Hi Michael,

The handler change is because the aws' module default handler is main.Main and when I built the ami_cleaner function and deployed it, the correct handler for it to properly work was "ami-cleaner".

The permissions issue is regarding this part of the code while checking for unused images

// Now, we use that filter to create an input into DescribeInstances.
findInstancesInput := &ec2.DescribeInstancesInput{
Filters: []*ec2.Filter{amiFilter},
}


Regards,
Guilherme Assad
Linux System Engineer
[cid:baec7484-61fb-4b79-822f-2fcd9644c2ad]
***@***.*** | T. +31(0) 20 760 22 00 | M.
 Emesa Nederland B.V. | Emesa Holdings B.V. | Spaklerweg 50 | 1114 AE Amsterdam ‑ Duivendrecht | www.emesa.nl<http://www.emesa.nl/> |
http://www.VakantieVeilingen.nl<http://www.vakantieveilingen.nl/>
http://www.VakantieVeilingen.be<http://www.vakantieveilingen.be/>
http://www.ActievandeDag.nl<http://www.actievandedag.nl/>
http://www.ActievandeDag.be<http://www.actievandedag.be/>
http://www.SlaJeSlag.nl<http://www.slajeslag.nl/>
http://www.VavaBid.be<http://www.vavabid.be/>
Please consider the environment before printing this e-mail.
​
​The information contained in messages (with attachments) from Emesa Holdings BV Emesa/Nederland BV May be confidential or privileged and is only intended for the use of the receiver named. If you are not the intended recipient, you are requested by Emesa to delete the message, with attachments without opening it and you are notified by Emesa Holdings BV/Emesa Nederland BV that any disclosure, copying or distribution of the information contained in the message (with attachments) is strictly prohibited and unlawful.
________________________________

Vriendelijke groet,
Guilherme Assad
Linux System Engineer
***@***.*** | T. +31(0) 20 760 22 00 | M. 
 Emesa Nederland B.V. | Emesa Holdings B.V. | Spaklerweg 50 | 1114 AE Amsterdam - Duivendrecht | www.emesa.nl | 
http://www.VakantieVeilingen.nl
http://www.VakantieVeilingen.be
http://www.ActievandeDag.nl
http://www.ActievandeDag.be
http://www.SlaJeSlag.nl
http://www.VavaBid.be
Please consider the environment before printing this e-mail.
​
​The information contained in messages (with attachments) from Emesa Holdings BV Emesa/Nederland BV May be confidential or privileged and is only intended for the use of the receiver named. If you are not the intended recipient, you are requested by Emesa to delete the message, with attachments without opening it and you are notified by Emesa Holdings BV/Emesa Nederland BV that any disclosure, copying or distribution of the information contained in the message (with attachments) is strictly prohibited and unlawful.

**Comment by tgraskemper** [comment]
I can confirm that the changes being reviewed here resolved our issues with using this module and the lambda.  Thanks @guilhermeassad and all contributors!

**Comment by tgraskemper** [comment]
@dynamike Any chance this could be merged?  We have this implemented on our side but would like to continue to run the module without those being reverted.

**Review by dynamike — APPROVED** [review]

**Pull request merged**
